# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed70108f5a9b229a805f42bba72251d9b22b248882817ccdf362e9e3452da84d92413ba14b0f09fdb197335d027b54ea028bbbdeaf4b805c63167e13e49ba457

test:
  secret_key_base: 0568b53bddfbeaa27887c320e17c365c32eed6f6c02348e0afadb631078a63e614dea56e023986101c3ae8b3268c530e220da0e82ac3eb900cdcabce18da7c40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
